name: 'Download a Build Artifact'
description: 'Download a build artifact that was previously uploaded in the workflow by the upload-artifact action'
author: 'GitHub'
inputs: 
  name:
    description: 'Artifact name'
    required: false
  path:
    description: 'Destination path'
    required: false
  maxTries:
    description: 'The integer number of times to try downloading a single artifact (requires `name`)'
    required: false
    default: '1'
  retryDelayMs:
    description: 'The integer number of milliseconds to wait after a failed download attempt before retrying (requires `name`)'
    required: false
    default: '60000'
runs:
  using: 'node16'
  main: 'dist/index.js'
